### ISSUE TITLE
Kivy TextInput focus is not working

### ISSUE THREAD

**Issue by cjaramilu** [qpython-mobile/qpython.org#24]
Focusing on the TextInput ends this script on an Android phone.
There is no error message in the Runtime Log.
The error does not occur when the script is run in the PC.
The error occurs after Qpython switched to Kivy 1.8

Simple script to replicate the problem:
from kivy.lang import Builder
from kivy.base import runTouchApp
from kivy.uix.boxlayout import BoxLayout
from kivy.uix.textinput  import TextInput
from kivy.uix.label        import Label
Builder.load_string("""
# :import kivy kivy
# :import sys sys

<Home>:
    orientation: "vertical"
    Label:
        text: "testing textinput problem"
    TextInput:
        text: "123"
    Label:
        text: "kivy version %s"  %   kivy.**version** 
 """)
 class Home (BoxLayout):
    pass
 runTouchApp (Home() )

**Comment by funs** [comment]
The same issue that happens to me, how to solve? Thanks!

**Comment by cjaramilu** [comment]
unfortunately the problem isn't solved yet.

Sent from my HTC

----- Reply message -----

**Comment by funs** [comment]
Thanks a lot.
